export const FETCH_USER_DATA = 'FETCH_USER_DATA';

export const FETCH_USER_POSTS = 'FETCH_USER_POSTS';
export const FETCH_USER_POSTS_BEGIN = 'FETCH_USER_POSTS_BEGIN';
export const FETCH_USER_POSTS_ERROR = 'FETCH_USER_POSTS_ERROR';
